- templates/base.html
- templates/photo-gallery.html
This pull request fixes a bug in the login functionality where users were unable to log in due to an error in the authentication process. The issue was caused by a missing parameter in the API request. This PR adds the missing parameter and ensures that users can successfully log in.
> Fix bug in login functionality

- static/css/vue-magnify.css
- templates/photo-gallery.html
This pull request updates the image sizes in the photo gallery to be 1000px by 1000px and fixes a typo in the code.
> Update image sizes and fix typo in photo gallery

- templates/base.html
- templates/photo-gallery.html
This pull request adds a dropdown menu to the user icon in the header. The dropdown menu includes options for the admin panel, login, and logout. Additionally, the user's role is checked to determine which options are displayed in the dropdown menu.
> #20 Add dropdown menu to user icon in header

- templates/photo-gallery.html
This pull request updates the `isAdmin` flag in the `photo-gallery.html` file. The flag is changed from `true` to `false`.
> #20 Update isAdmin flag in photo-gallery.html

- app.py
- templates/index.html
This pull request adds functionality to the index.html file to display a photo gallery. It also updates the route for the photo gallery from '/gallery/photo' to '/gallery/images'.
> #23 Add photo gallery functionality and update route

- app.py
- templates/admin/base.html
- templates/admin/socials.html
This pull request adds a new route and template for the admin/socials page. The route is accessible to admin users only and renders the socials.html template, which displays a heading "Socials".
> Add admin/socials route and template

- templates/index.html
All images are lazy loading now
> added lazy loading to all imgs

- static/js/scripts.js
- templates/index.html
> #47 Delay effects and Disable controls 

- app.py
- templates/base.html
- templates/bikes.html
- templates/product-details.html
> #33 Products details page flask update

- templates/about-orangecat.html
- templates/index.html
- redirected know more button to history section of about page
- removed empty lines
- redirected read more button from home page to about page
> redirected know more button to history section of about page

- templates/base.html
- templates/index.html
- templates/product-details.html
replaced the bikes with models
> replaced the bikes with models

- templates/index.html
changed the Our Products heading to Our Cycles
> changed the Our Products heading to Our Cycles

- static/css/style.css
- templates/product-details.html
- Used cards for displaying accessories and details for product details 
- Removed table view
> used cards for displaying accessories and details for product details

- AWS_Modules.py
- app.py
- templates/admin/base.html
- templates/admin/settings.html
#82 Funtionality to delete all the iimages from S3 and the db - please reset all the local db to accomodate for this changes
> #82 Delete all images from S3

- templates/about-orangecat.html
> About Us Pager - FAQ #89

- static/css/style.css
- templates/bikes.html
enquire button not clickable issue solved
> Enquire button not clickable issue solved_issue_87

- static/css/style.css
mobile responsiveness issue of feedback section solved
> mobile responsiveness issue of feedback section

- .gitignore
- templates/index.html
This pull request includes the following changes:
- Added "instance/" to .gitignore
- Updated the video source in index.html to use "bgvideo3.mp4"
- Added a new hero background video
> #98 Update .gitignore and video source, add new hero bg video

- templates/index.html
> vide changed

- static/css/style.css
- templates/about-orangecat.html
Removed duplicate contents from about page
> Duplicate contents in about page

- static/css/style.css
Aligned FAQ texts to left in about page for mobile view_#122
> Aligned FAQ texts to left_#122

- static/css/style.css
Texts aligned to left in FAQ section to make responsive
> Responsive FAQ Section

- templates/base.html
Footer bottom text changed to Nexeor
> Footer bottom text changed to Nexeor

- templates/arrow.html
- templates/bow.html
Proper page links are added to "Know More" button of related products
> "Know More" Button Not Working in Related Products Section_#134

- app.py
- requirements.txt
- static/css/style.css
- static/js/scripts.js
- templates/base.html
This pull request includes backend development tasks for the transition of our website to an e-commerce model. It implements database models for users, addresses, orders, and products. It also develops APIs for user and order management, integrates Stripe for payment processing, and implements email notifications for various user actions. Additionally, it ensures API security, error handling, data validation, and automated tests. Fixes #151
> #151 Backend Development for E-commerce Transition and Stripe Integration

- app.py
- templates/profile.html
Implement backend functionalities to support the transition of our website to an e-commerce model. This includes setting up database models, creating APIs for user and order management, integrating Stripe for payment processing, and implementing email notifications for various user actions.
Backend Tasks:
- Users: Store user information including authentication data.
API Development:
- User Authentication: APIs for user login and signup.
- User Profile Management: Allow users to update their profile and manage their credentials.
- Signup Confirmation: Send a confirmation email upon successful signup.
.
- Integrate error handling and data validation across all backend processes.
> #151 #149 Backend Development for E-commerce Transition and Stripe Integration

- static/css/style.css
- templates/checkout.html
> checkout page update

- app.py
- templates/checkout.html
This pull request refactors the save_order_data route to handle POST requests instead of GET requests. It also improves error handling and adds appropriate error messages. This change ensures that the order data is saved correctly and provides a better user experience.
Fixes #151 #148
> Refactor save_order_data route to handle POST requests and improve error handling #151 #148

- app.py
This pull request adds password hashing for user authentication to enhance security and protect user credentials. It uses the `generate_password_hash` function from the `werkzeug.security` module to securely hash passwords before storing them in the database. This ensures that user passwords are not stored in plain text and provides an additional layer of protection against unauthorized access.
Fixes #151
> Add password hashing for user authentication

- app.py
- templates/login.html
- templates/signup.html
This pull request fixes two issues related to user creation and login. The first issue was that users were able to create an account without providing any details. This has been fixed by adding form validation to the user signup form. The second issue was that users were able to login after updating their details on the profile page without providing all the required information. This has been fixed by adding the required attribute to the email, password, and confirm_password fields in both the login and signup forms. These changes ensure that users cannot create an account or login without providing all the necessary details.
> Fix user creation and login issues #176

- templates/orders.html
> Refactor order display in orders.html #167

- static/data/product-data.json
#136 Spelling mistake corrected
> Fix the Typo - Solved

- templates/signup.html
> Fix issues with user creation and login #176
